2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_setup.py:_flush():76] Configure stats pid to 34044
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_setup.py:_flush():76] Loading settings from C:\Users\CARLOS\.config\wandb\settings
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_setup.py:_flush():76] Loading settings from C:\Users\CARLOS\OneDrive\ICESI\Maestria Ciencia de Datos\Semestre2\Fundamentos de analítica II\MCD_FAII\FAII\Talleres\Taller_Practico\wandb\settings
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'silent': 'True', 'entity': 'ceja0919', 'project': 'MCD_FA_II_T1', 'root_dir': 'C:\\Users\\CARLOS\\OneDrive\\ICESI\\Maestria Ciencia de Datos\\Semestre2\\Fundamentos de analítica II\\MCD_FAII\\FAII\\Talleres\\Taller_Practico', 'run_id': '2plmvde1', 'sweep_param_path': 'C:\\Users\\CARLOS\\OneDrive\\ICESI\\Maestria Ciencia de Datos\\Semestre2\\Fundamentos de analítica II\\MCD_FAII\\FAII\\Talleres\\Taller_Practico\\wandb\\sweep-mdhbgc4z\\config-2plmvde1.yaml', 'sweep_id': 'mdhbgc4z'}
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_init.py:_log_setup():527] Logging user logs to C:\Users\CARLOS\OneDrive\ICESI\Maestria Ciencia de Datos\Semestre2\Fundamentos de analítica II\MCD_FAII\FAII\Talleres\Taller_Practico\wandb\run-20240327_193908-2plmvde1\logs\debug.log
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_init.py:_log_setup():528] Logging internal logs to C:\Users\CARLOS\OneDrive\ICESI\Maestria Ciencia de Datos\Semestre2\Fundamentos de analítica II\MCD_FAII\FAII\Talleres\Taller_Practico\wandb\run-20240327_193908-2plmvde1\logs\debug-internal.log
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_init.py:_jupyter_setup():473] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002AE94D36410>
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_init.py:init():567] calling init triggers
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_init.py:init():574] wandb.init called with sweep_config: {'gamma': 3.328620046920448, 'imputer': 'knn', 'imputer_strategy': 'mean', 'knn_imputer_k': 10, 'learning_rate': 0.004346831206593096, 'max_depth': 10, 'min_child_weight': 9, 'n_estimators': 322, 'reg_alpha': 7, 'reg_lambda': 4, 'scaler': 'standard', 'variance_threshold': 0.049048298418489705}
config: {}
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_init.py:init():617] starting backend
2024-03-27 19:39:08,725 INFO    Thread-39 (_run_job):34044 [wandb_init.py:init():621] setting up manager
2024-03-27 19:39:08,739 INFO    Thread-39 (_run_job):34044 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-27 19:39:08,739 INFO    Thread-39 (_run_job):34044 [wandb_init.py:init():629] backend started and connected
2024-03-27 19:39:08,797 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_config_callback():1347] config_cb None None {'gamma': 3.328620046920448, 'imputer': 'knn', 'imputer_strategy': 'mean', 'knn_imputer_k': 10, 'learning_rate': 0.004346831206593096, 'max_depth': 10, 'min_child_weight': 9, 'n_estimators': 322, 'reg_alpha': 7, 'reg_lambda': 4, 'scaler': 'standard', 'variance_threshold': 0.049048298418489705}
2024-03-27 19:39:08,797 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-03-27 19:39:08,797 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-27 19:39:08,797 INFO    Thread-39 (_run_job):34044 [wandb_init.py:init():721] updated telemetry
2024-03-27 19:39:08,873 INFO    Thread-39 (_run_job):34044 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-03-27 19:39:09,207 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_on_init():2344] communicating current version
2024-03-27 19:39:09,309 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_on_init():2353] got version response 
2024-03-27 19:39:09,309 INFO    Thread-39 (_run_job):34044 [wandb_init.py:init():805] starting run threads in backend
2024-03-27 19:39:25,849 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_console_start():2323] atexit reg
2024-03-27 19:39:25,849 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_redirect():2178] redirect: wrap_raw
2024-03-27 19:39:25,849 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_redirect():2243] Wrapping output streams.
2024-03-27 19:39:25,849 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_redirect():2268] Redirects installed.
2024-03-27 19:39:25,849 INFO    Thread-39 (_run_job):34044 [wandb_init.py:init():848] run started, returning control to user process
2024-03-27 19:39:27,518 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_finish():2052] finishing run ceja0919/MCD_FA_II_T1/2plmvde1
2024-03-27 19:39:27,518 INFO    Thread-39 (_run_job):34044 [jupyter.py:save_history():445] not saving jupyter history
2024-03-27 19:39:27,518 INFO    Thread-39 (_run_job):34044 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-27 19:39:27,518 INFO    Thread-39 (_run_job):34044 [wandb_init.py:_jupyter_teardown():455] cleaning up jupyter logic
2024-03-27 19:39:27,518 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 1
2024-03-27 19:39:27,518 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_restore():2275] restore
2024-03-27 19:39:27,518 INFO    Thread-39 (_run_job):34044 [wandb_run.py:_restore():2281] restore done
